
CREATE TABLE TOP_EDITORS
( 
  TOP_ID INT(2) NOT NULL,
  EDITOR_NAME VARCHAR(20) NOT NULL,
  CONSTRAINT TOP_PK PRIMARY KEY (TOP_ID)
);

INSERT INTO TOP_EDITORS VALUES(1, 'ATOM');
INSERT INTO TOP_EDITORS VALUES(2, 'VISUAL STUDIO CODE');
INSERT INTO TOP_EDITORS VALUES(3, 'BRACKETS');
INSERT INTO TOP_EDITORS VALUES(4, 'SUBLIME TEXT');
INSERT INTO TOP_EDITORS VALUES(5, 'LIGHT TABLE');
